/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuloSeguridad.GUI;
import ModuloAdministracion.GUIWindows.frmAdministracion;

import java.awt.Dimension;

/**
 *
 * @author Jean Paul Mosquera Arevalo
 */
public class Administrador extends javax.swing.JInternalFrame {
    Rusuarios registroUsuarios = null;
    frmAdministracion col=null;
    Rroles registroRoles = null;
    Rfuncionalidades registroFuncionalidades=null;
    RolUsuario controlUsuario=null;
    RolFuncion controlRoles=null;
    String usuarioPrivilegiado="admin";
    public Administrador() {
        this.setResizable(true);
        this.setClosable(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        registroU = new javax.swing.JMenuItem();
        registroR = new javax.swing.JMenuItem();
        registroF = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        cUsuarioRol = new javax.swing.JMenuItem();
        cRolFuncion = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1253, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );

        jMenu2.setText("Registro y Edicion");

        registroU.setText("Usuarios");
        registroU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroUActionPerformed(evt);
            }
        });
        jMenu2.add(registroU);

        registroR.setText("Roles");
        registroR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroRActionPerformed(evt);
            }
        });
        jMenu2.add(registroR);

        registroF.setText("Funcionalidades");
        registroF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroFActionPerformed(evt);
            }
        });
        jMenu2.add(registroF);

        jMenuItem1.setText("Colecciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Asignacion");

        cUsuarioRol.setText("Usuario-Rol");
        cUsuarioRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUsuarioRolActionPerformed(evt);
            }
        });
        jMenu3.add(cUsuarioRol);

        cRolFuncion.setText("Funcionalidades-Rol");
        cRolFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cRolFuncionActionPerformed(evt);
            }
        });
        jMenu3.add(cRolFuncion);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroRActionPerformed

        registroRoles= new Rroles();
        registroRoles.setVisible(true);
        registroRoles.getContentPane().setPreferredSize(new Dimension(jDesktopPane.getWidth(),jDesktopPane.getHeight()));
        registroRoles.pack();
        jDesktopPane.add(registroRoles);
        if (registroUsuarios!=null){
            registroUsuarios.dispose();
        } 
        if (registroFuncionalidades!=null){
            registroFuncionalidades.dispose();
        } 
        if (controlUsuario!=null){
            controlUsuario.dispose();
        } 
        if (controlRoles!=null){
            controlRoles.dispose();
        } 
        if(col!=null){
            col.dispose();
        }               
    }//GEN-LAST:event_registroRActionPerformed

    private void registroUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroUActionPerformed
        registroUsuarios= new Rusuarios();
        registroUsuarios.setVisible(true);
        registroUsuarios.getContentPane().setPreferredSize(new Dimension(jDesktopPane.getWidth(),jDesktopPane.getHeight()));
        registroUsuarios.pack();
        jDesktopPane.add(registroUsuarios);
        if (registroRoles!=null){
            registroRoles.dispose();
        } 
        if (registroFuncionalidades!=null){
            registroFuncionalidades.dispose();
        } 
        if (controlUsuario!=null){
            controlUsuario.dispose();
        } 
        if (controlRoles!=null){
            controlRoles.dispose();
        } 
         if(col!=null){
            col.dispose();
        }              
        
    }//GEN-LAST:event_registroUActionPerformed

    private void registroFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroFActionPerformed
         registroFuncionalidades= new Rfuncionalidades();
        registroFuncionalidades.setVisible(true);
        registroFuncionalidades.getContentPane().setPreferredSize(new Dimension(jDesktopPane.getWidth(),jDesktopPane.getHeight()));
        registroFuncionalidades.pack();
        jDesktopPane.add(registroFuncionalidades);
        if (registroRoles!=null){
            registroRoles.dispose();
        } 
        if (registroUsuarios!=null){
            registroUsuarios.dispose();
        } 
        if (controlUsuario!=null){
            controlUsuario.dispose();
        } 
        if (controlRoles!=null){
            controlRoles.dispose();
        } 
        if(col!=null){
            col.dispose();
        }                    
         
    }//GEN-LAST:event_registroFActionPerformed

    private void cRolFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cRolFuncionActionPerformed
        controlRoles= new RolFuncion();
        controlRoles.setVisible(true);
        controlRoles.getContentPane().setPreferredSize(new Dimension(jDesktopPane.getWidth(),jDesktopPane.getHeight()));
        controlRoles.pack();
        jDesktopPane.add(controlRoles);
        if (registroRoles!=null){
            registroRoles.dispose();
        } 
        if (registroUsuarios!=null){
            registroUsuarios.dispose();
        } 
        if (registroFuncionalidades!=null){
            registroFuncionalidades.dispose();
        } 
        if (controlUsuario!=null){
            controlUsuario.dispose();
        } 
        if(col!=null){
            col.dispose();
        }
    
    }//GEN-LAST:event_cRolFuncionActionPerformed

    private void cUsuarioRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUsuarioRolActionPerformed
        controlUsuario= new RolUsuario();
        controlUsuario.setVisible(true);
        controlUsuario.getContentPane().setPreferredSize(new Dimension(jDesktopPane.getWidth(),jDesktopPane.getHeight()));
        controlUsuario.pack();
        jDesktopPane.add(controlUsuario);
        if (registroRoles!=null){
            registroRoles.dispose();
        }
        if (registroUsuarios!=null){
            registroUsuarios.dispose();
        }
        if (registroFuncionalidades!=null){
            registroFuncionalidades.dispose();
        }
        if (controlRoles!=null){
            controlRoles.dispose();
        }
        if(col!=null){
            col.dispose();
        }


    }//GEN-LAST:event_cUsuarioRolActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        col= new frmAdministracion();
        col.setVisible(true);
        int centrox=jDesktopPane.getWidth()/2;
        int centroy=jDesktopPane.getHeight()/2;
        col.getContentPane().setLocation(centrox, centroy);
        col.getContentPane().setPreferredSize(new Dimension(jDesktopPane.getWidth(),jDesktopPane.getHeight()));
        col.getContentPane().setPreferredSize(new Dimension(jDesktopPane.getWidth(),jDesktopPane.getHeight()));
        col.pack();
        jDesktopPane.add(col);
        if (registroRoles!=null){
            registroRoles.dispose();
        } 
        if (registroFuncionalidades!=null){
            registroFuncionalidades.dispose();
        } 
        if (controlUsuario!=null){
            controlUsuario.dispose();
        } 
        if (controlRoles!=null){
            controlRoles.dispose();
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cRolFuncion;
    private javax.swing.JMenuItem cUsuarioRol;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem registroF;
    private javax.swing.JMenuItem registroR;
    private javax.swing.JMenuItem registroU;
    // End of variables declaration//GEN-END:variables
}
