/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuloSeguridad.GUI;

import ModuloSeguridad.BL.BLUsuarios;
import ModuloSeguridad.Clases.Usuario;
import ModuloSeguridad.Clases.Security;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jean Paul Mosquera Arevalo
 */
public class Rroles extends javax.swing.JInternalFrame {
      int row;
      String id;
      int idB;
      String strNombre=null;
      String strDescripcion=null;
      BLUsuarios mp= new BLUsuarios();

    public Rroles() {
          try {
              initComponents();
              LlenarTabla();
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Rroles.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(Rroles.class.getName()).log(Level.SEVERE, null, ex);
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        space = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnRegistrarR = new javax.swing.JButton();
        btnCargarT3 = new javax.swing.JButton();
        btnModificarR = new javax.swing.JButton();
        btnEliminarR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(java.awt.SystemColor.windowBorder);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registro de Roles");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese toda la información a continuación detalla");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(534, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        space.setBackground(new java.awt.Color(140, 177, 19));

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre");

        lblDescripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setText("Descripcion");

        javax.swing.GroupLayout spaceLayout = new javax.swing.GroupLayout(space);
        space.setLayout(spaceLayout);
        spaceLayout.setHorizontalGroup(
            spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(spaceLayout.createSequentialGroup()
                        .addComponent(lblDescripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(spaceLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        spaceLayout.setVerticalGroup(
            spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spaceLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(140, 177, 19));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visualización de Roles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        jPanel7.setBackground(java.awt.SystemColor.windowBorder);

        btnRegistrarR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistrarR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ModuloSeguridad/recursos/add.png"))); // NOI18N
        btnRegistrarR.setText("<html><b>Registrar<br>Rol</b></html>\"  ");
        btnRegistrarR.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnRegistrarR.setMaximumSize(new java.awt.Dimension(20, 30));
        btnRegistrarR.setMinimumSize(new java.awt.Dimension(30, 20));
        btnRegistrarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRActionPerformed(evt);
            }
        });

        btnCargarT3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCargarT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ModuloSeguridad/recursos/refresh.png"))); // NOI18N
        btnCargarT3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCargarT3.setMaximumSize(new java.awt.Dimension(20, 30));
        btnCargarT3.setMinimumSize(new java.awt.Dimension(30, 20));
        btnCargarT3.setPreferredSize(new java.awt.Dimension(79, 35));
        btnCargarT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarT3ActionPerformed(evt);
            }
        });

        btnModificarR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificarR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ModuloSeguridad/recursos/editar.png"))); // NOI18N
        btnModificarR.setText("<html><b>Modificar<br>Rol</b></html>\"   ");
        btnModificarR.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnModificarR.setMaximumSize(new java.awt.Dimension(20, 30));
        btnModificarR.setMinimumSize(new java.awt.Dimension(30, 20));
        btnModificarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarRActionPerformed(evt);
            }
        });

        btnEliminarR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminarR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ModuloSeguridad/recursos/delete.png"))); // NOI18N
        btnEliminarR.setText("<html><b>Eliminar<br>Rol</b></html>\"  ");
        btnEliminarR.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnEliminarR.setMaximumSize(new java.awt.Dimension(20, 30));
        btnEliminarR.setMinimumSize(new java.awt.Dimension(30, 20));
        btnEliminarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnRegistrarR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnModificarR, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnEliminarR, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(btnCargarT3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificarR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargarT3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(space, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(space, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void LimpiarTextField(JTextField txtField){
        txtField.setText("");
    }
    
    public void  LimpiarPasswordField(JPasswordField txtPassword){
        txtPassword.setText((""));
    }
    public void LimpiarFormattedField(JFormattedTextField txtF){
        txtF.setText("");
    }
        public void ValidaryEscribir() throws ClassNotFoundException, SQLException{
        strNombre=txtNombre.getText();
        strDescripcion=txtDescripcion.getText();
        boolean encontrado=mp.validarRol(strNombre);
        if (!strNombre.equals("")&&!strDescripcion.equals("")) { 
                    if(encontrado){
                         JOptionPane.showMessageDialog(rootPane ,"Rol Registrado","Advertencia",JOptionPane.ERROR_MESSAGE);
                    }else{
                    mp.InsertarRol(strNombre.toLowerCase(),strDescripcion.toLowerCase());
                    JOptionPane.showMessageDialog(rootPane ,"Registrado con Exito","Informe",JOptionPane.INFORMATION_MESSAGE);                        
                    }

        }else{
             JOptionPane.showMessageDialog(rootPane ,"Algunos campos estan vacios\n Ingrese informacion en los campos faltantes","Advertencia",JOptionPane.ERROR_MESSAGE);
        }
        }  
      public void Limpiar(){
                LimpiarTextField(txtNombre);
                LimpiarTextField(txtDescripcion);

      }

  public final void LlenarTabla() throws ClassNotFoundException, SQLException{
            //Como el método de la BL retorna un ArrayList de la clase Estudiantes
            //Aqui lo recuperamos
            ArrayList<Usuario> lstusuarios = mp.ListaRol();
           
            Object columnas[] = {"ID","Nombre", "Descripcion"};
            DefaultTableModel modelo = new DefaultTableModel(null, columnas);
            jTable3.setModel(modelo); 
            
            for (Usuario objeto : lstusuarios)
            {
                //String id=String.valueOf(objeto.getStrCodigo());
                String idC=String.valueOf(objeto.getIdRol());
                String nombre=String.valueOf(objeto.getNombreRol());
                String descripcion=String.valueOf(objeto.getDescripcionRol());
                String modeloTemp[] = {idC,nombre,descripcion,};
                modelo.addRow(modeloTemp);
            }
 }
       public void EliminarRol(){
    try { 
        mp.eliminarRolID(idB);
        LlenarTabla();
        JOptionPane.showMessageDialog(rootPane ,"Eliminado con Exito","Informe",JOptionPane.INFORMATION_MESSAGE);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Rusuarios.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        
       JOptionPane.showMessageDialog(rootPane ,"Imposible Eliminar existe asignados roles","Advertencia",JOptionPane.ERROR_MESSAGE);
    }
        
      }       
    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked

        row =(int)jTable3.getSelectedRow();
        id=(String)jTable3.getModel().getValueAt(row, 0);
        strNombre=(String)jTable3.getModel().getValueAt(row, 1);
        strDescripcion=(String)jTable3.getModel().getValueAt(row, 2);
        idB=Integer.parseInt(id);
        txtNombre.setText(strNombre);
        txtDescripcion.setText(strDescripcion);

        

 
    }//GEN-LAST:event_jTable3MouseClicked

    private void btnRegistrarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRActionPerformed
        // TODO add your handling code here:
                 try {
              // TODO add your handling code here:
              ValidaryEscribir();
              LlenarTabla();
              LimpiarTextField(txtNombre);
              LimpiarTextField(txtDescripcion);
              Limpiar();
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Rusuarios.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(Rusuarios.class.getName()).log(Level.SEVERE, null, ex);
          }
  
    }//GEN-LAST:event_btnRegistrarRActionPerformed

    private void btnCargarT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarT3ActionPerformed
        // TODO add your handling code here
         try {
              // TODO add your handling code here
              LlenarTabla();
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Rusuarios.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(Rusuarios.class.getName()).log(Level.SEVERE, null, ex);
          }
        
    }//GEN-LAST:event_btnCargarT3ActionPerformed

    private void btnModificarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarRActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        DefaultTableModel modelo=(DefaultTableModel)jTable3.getModel();
            if (row>=0) {
                //Se modifica los valores ingresados por el usuario
                strNombre=txtNombre.getText();
                strDescripcion=txtDescripcion.getText();
                
                mp.modificarRolID(idB, strNombre,strDescripcion);


                JOptionPane.showMessageDialog(this, "ROl Modificada con Exito","Informacion",JOptionPane.INFORMATION_MESSAGE);
                //Se emplea el metodo limpiarCampos
                Limpiar();
            }else{
                //Si el usuario no selecciona una fila se advertira con una notificacion
                JOptionPane.showMessageDialog(this, "Seleccione una Fila","Advertencia",JOptionPane.WARNING_MESSAGE);
            }

        // </editor-fold>
    }//GEN-LAST:event_btnModificarRActionPerformed

    private void btnEliminarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRActionPerformed
  EliminarRol();
  Limpiar();
    }//GEN-LAST:event_btnEliminarRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rroles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rroles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rroles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rroles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rroles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarT3;
    private javax.swing.JButton btnEliminarR;
    private javax.swing.JButton btnModificarR;
    private javax.swing.JButton btnRegistrarR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel space;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
