/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModuloSeguridad.GUI;

import ModuloSeguridad.BL.BLUsuarios;
import ModuloSeguridad.Clases.Usuario;
import ModuloSeguridad.Clases.Security;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jean Paul Mosquera Arevalo
 */
public class Rusuarios extends javax.swing.JInternalFrame {
      int row;
      String id;
      int idB;
      String strNombre=null;
      String strDNI=null;
      String strApellido=null;
      String strUsername=null;
      String strPassword=null;
      BLUsuarios mp= new BLUsuarios();
      int intUsuarioId = 0;


    /**
     * Creates new form Rusuarios
     */
    public Rusuarios() {
        
          try {
              initComponents();
              LlenarTabla();
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Rusuarios.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(Rusuarios.class.getName()).log(Level.SEVERE, null, ex);
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        space = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnRegistrarU = new javax.swing.JButton();
        btnCargarT3 = new javax.swing.JButton();
        btnModificarU = new javax.swing.JButton();
        btnEliminarU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(java.awt.SystemColor.windowBorder);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registro de Usuarios");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese toda la información a continuación detalla");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        space.setBackground(new java.awt.Color(140, 177, 19));

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");

        lblApellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos.setText("Apellidos:");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario:");

        lblContrasenia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasenia.setText("Contraseña:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DNI");
        jLabel2.setToolTipText("DNI");

        javax.swing.GroupLayout spaceLayout = new javax.swing.GroupLayout(space);
        space.setLayout(spaceLayout);
        spaceLayout.setHorizontalGroup(
            spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addComponent(lblContrasenia)
                    .addComponent(lblApellidos)
                    .addComponent(lblNombre)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txtUsername)
                    .addComponent(txtPassword)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(txtDni))
                .addGap(30, 30, 30))
        );
        spaceLayout.setVerticalGroup(
            spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(spaceLayout.createSequentialGroup()
                        .addGroup(spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(spaceLayout.createSequentialGroup()
                                .addGroup(spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNombre)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addComponent(lblApellidos))
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(lblUsuario))
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(spaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasenia)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(140, 177, 19));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visualización de Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel7.setBackground(java.awt.SystemColor.windowBorder);

        btnRegistrarU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistrarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ModuloSeguridad/recursos/anadir1.png"))); // NOI18N
        btnRegistrarU.setText("<html><b>Registrar<br>Usuario</b></html>\"  ");
        btnRegistrarU.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnRegistrarU.setMaximumSize(new java.awt.Dimension(20, 30));
        btnRegistrarU.setMinimumSize(new java.awt.Dimension(30, 20));
        btnRegistrarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUActionPerformed(evt);
            }
        });

        btnCargarT3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCargarT3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ModuloSeguridad/recursos/refresh.png"))); // NOI18N
        btnCargarT3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnCargarT3.setMaximumSize(new java.awt.Dimension(20, 30));
        btnCargarT3.setMinimumSize(new java.awt.Dimension(30, 20));
        btnCargarT3.setPreferredSize(new java.awt.Dimension(79, 35));
        btnCargarT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarT3ActionPerformed(evt);
            }
        });

        btnModificarU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ModuloSeguridad/recursos/editar.png"))); // NOI18N
        btnModificarU.setText("<html><b>Modificar<br>Usuario</b></html>\"   ");
        btnModificarU.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnModificarU.setMaximumSize(new java.awt.Dimension(20, 30));
        btnModificarU.setMinimumSize(new java.awt.Dimension(30, 20));
        btnModificarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUActionPerformed(evt);
            }
        });

        btnEliminarU.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEliminarU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ModuloSeguridad/recursos/delete.png"))); // NOI18N
        btnEliminarU.setText("<html><b>Eliminar<br>Usuario</b></html>\"  ");
        btnEliminarU.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnEliminarU.setMaximumSize(new java.awt.Dimension(20, 30));
        btnEliminarU.setMinimumSize(new java.awt.Dimension(30, 20));
        btnEliminarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnRegistrarU, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnModificarU, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnEliminarU, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addComponent(btnCargarT3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificarU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCargarT3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(space, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(space, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void LimpiarTextField(JTextField txtField){
        txtField.setText("");
    }
    
    public void  LimpiarPasswordField(JPasswordField txtPassword){
        txtPassword.setText((""));
    }
    public void LimpiarFormattedField(JFormattedTextField txtF){
        txtF.setText("");
    }
        public void ValidaryEscribir() throws ClassNotFoundException, SQLException{
        strDNI=txtDni.getText();
        strNombre=txtNombre.getText();
        strApellido=txtApellido.getText();
        strUsername=txtUsername.getText();
        strPassword= txtPassword.getText();
        if (!strNombre.equals("")&&!strApellido.equals("")&&!strUsername.equals("")&&!strPassword.equals("")) { 
            boolean encontrado=mp.validarUs(strDNI,strUsername);
            if (encontrado) {
                JOptionPane.showMessageDialog(rootPane ,"DNI ya Registrado","Advertencia",JOptionPane.ERROR_MESSAGE);
            }else{

                                  mp.InsertarUsuario(strDNI,strNombre.toUpperCase(),strApellido.toUpperCase(),strUsername,Security.encodeWithAES(Security.key,strPassword));   
                        JOptionPane.showMessageDialog(rootPane ,"Registrado con Exito","Informe",JOptionPane.INFORMATION_MESSAGE);   
   
            }
        }else{
             JOptionPane.showMessageDialog(rootPane ,"Algunos campos estan vacios\n Ingrese informacion en los campos faltantes","Advertencia",JOptionPane.ERROR_MESSAGE);
        }
        }  
      public void Limpiar(){
                LimpiarTextField(txtNombre);
                LimpiarTextField(txtApellido);
                LimpiarTextField(txtUsername);
                LimpiarPasswordField(txtPassword);

      }

  public final void LlenarTabla() throws ClassNotFoundException, SQLException{
            //Como el método de la BL retorna un ArrayList de la clase Estudiantes
            //Aqui lo recuperamos
            ArrayList<Usuario> lstusuarios = mp.ListaUsuarios();
           
            Object columnas[] = {"us_id","us_nombre", "us_apellido","us_login","us_password"};
            DefaultTableModel modelo = new DefaultTableModel(null, columnas);
            jTable3.setModel(modelo); 
            
            for (Usuario objeto : lstusuarios)
            {
                //String id=String.valueOf(objeto.getStrCodigo());
                String idC=String.valueOf(objeto.getIdUsuario());
                String nombre=String.valueOf(objeto.getNombreUsuario());
                String apellido=String.valueOf(objeto.getApellidoUsuario());
                String login=String.valueOf(objeto.getUsername());
                String strPasswordE=objeto.getPassword();
                String strPasswordD=Security.decodeWithAES(Security.key, strPasswordE);
                String modeloTemp[] = {idC,nombre,apellido,login, strPasswordD};
                modelo.addRow(modeloTemp);
            }
 }
       public void EliminarUsuario(){
    try { 
        mp.eliminarUsuarioID(idB);
        LlenarTabla();
        JOptionPane.showMessageDialog(rootPane ,"Eliminado con Exito","Informe",JOptionPane.INFORMATION_MESSAGE);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Rusuarios.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        
       JOptionPane.showMessageDialog(rootPane ,"Imposible Eliminar existe asignados roles","Advertencia",JOptionPane.ERROR_MESSAGE);
    }
        
      }       



  
// </editor-fold>           
    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:

        row =(int)jTable3.getSelectedRow();
        id=(String)jTable3.getModel().getValueAt(row, 0);
        strNombre=(String)jTable3.getModel().getValueAt(row, 1);
        strApellido=(String)jTable3.getModel().getValueAt(row, 2);
        strUsername=(String)jTable3.getModel().getValueAt(row, 3);
        strPassword=(String)jTable3.getModel().getValueAt(row, 4);
        idB=Integer.parseInt(id);
        txtNombre.setText(strNombre);
        txtApellido.setText(strApellido);
        txtUsername.setText(strUsername);
        txtPassword.setText(strPassword);
        
   


    }//GEN-LAST:event_jTable3MouseClicked

    private void btnRegistrarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUActionPerformed
          try {
              // TODO add your handling code here:
              ValidaryEscribir();
              LlenarTabla();
              LimpiarTextField(txtNombre);
              LimpiarTextField(txtApellido);
              LimpiarTextField(txtUsername);
              LimpiarPasswordField(txtPassword);
              Limpiar();
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Rusuarios.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(Rusuarios.class.getName()).log(Level.SEVERE, null, ex);
          }

    }//GEN-LAST:event_btnRegistrarUActionPerformed

    private void btnCargarT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarT3ActionPerformed
          try {
              // TODO add your handling code here
              LlenarTabla();
          } catch (ClassNotFoundException ex) {
              Logger.getLogger(Rusuarios.class.getName()).log(Level.SEVERE, null, ex);
          } catch (SQLException ex) {
              Logger.getLogger(Rusuarios.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_btnCargarT3ActionPerformed

    private void btnModificarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo=(DefaultTableModel)jTable3.getModel();
            if (row>=0) {
                //Se modifica los valores ingresados por el usuario
                strNombre=txtNombre.getText();
                strApellido=txtApellido.getText();
                strUsername=txtUsername.getText();
                strPassword=txtPassword.getText();
                
                mp.modificarUsuarioID(idB, strNombre, strApellido, strUsername,Security.encodeWithAES(Security.key,strPassword) );


                JOptionPane.showMessageDialog(this, "ROl Modificada con Exito","Informacion",JOptionPane.INFORMATION_MESSAGE);
                //Se emplea el metodo limpiarCampos
                Limpiar();
            }else{
                //Si el usuario no selecciona una fila se advertira con una notificacion
                JOptionPane.showMessageDialog(this, "Seleccione una Fila","Advertencia",JOptionPane.WARNING_MESSAGE);
            }


        // </editor-fold>
    }//GEN-LAST:event_btnModificarUActionPerformed

    private void btnEliminarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUActionPerformed
         EliminarUsuario();
         Limpiar();
    }//GEN-LAST:event_btnEliminarUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rusuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rusuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarT3;
    private javax.swing.JButton btnEliminarU;
    private javax.swing.JButton btnModificarU;
    private javax.swing.JButton btnRegistrarU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel space;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
